### ISSUE TITLE
No Idea How To Use, Sorry

### ISSUE THREAD

**Issue by Snarr** [dada1134/discord-bans#4]
Hey, this 'import' which I've never seen in JavaScript before. When I try to use that
```import DiscordBans from 'discord-bans'```
line, the code crashes and I get error "Unexpected token import". 

When I try to require (like normal) I get this:
Error: Cannot find module 'discord-bans'

**Comment by dada1134** [comment]
The readme was in fact wrong. This should work:

```js
const { DiscordBans } = require('discord-bans')
```
Also make sure to update to v2.2.2.
